### ISSUE TITLE
Your app has an issue 

### ISSUE THREAD

**Issue by CodeAjay** [Rishav1707/Todo-List-Component#3]
Your app has an issue, I clicked on the add button with empty text and a todo list with empty title is added, that should not happen. 

![image](https://user-images.githubusercontent.com/58427577/235179516-c5e355d7-0a41-42f9-94fa-4f1517016721.png)

I want to fix this issue.

**Comment by Rishav1707** [comment]
Sure, go ahead🙌🏻

**Comment by debmalya37** [comment]
hey Rishav! is this issued already assigned ?? if not , I want to take on this issue !!

**Comment by CodeAjay** [comment]
Fixed the issue Please merge the PR #4

**Comment by Rishav1707** [comment]
> hey Rishav! is this issued already assigned ?? if not , I want to take on this issue !!

Already assigned to @CodeAjay

**Comment by Rishav1707** [comment]
Fixed🚀. Thank you @CodeAjay
